spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://61.164.242.135:3306/fljg?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: fljg
    password: ilovelaohan
  main:
    allow-bean-definition-overriding: true
    
  mvc:
    view:
      suffix: .jsp
      prefix: /
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
---
#spring:
#  profiles:
#    a
server:
  port: 8001
