server:  port: 9001  spring:  application:    name: eureka_server        eureka:  client:    service-url:      defaultZone: http://localhost:7001/eureka/    register-with-eureka: false    fetch-registry: false
