server:
  port: 7001
  
user: 
  serverUrl: http://provider/
  
spring:
  application:
    name: consumer
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
