server:
  port: 7001
  
user: 
  serverUrl: provider
  
spring:
  application:
    name: consumer
    
  mvc:
    view:
      prefix: /
      suffix: .jsp
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
